# Generated by Django 4.2.7 on 2024-02-24 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_payment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('open', 'открыт'), ('expired', 'просрочен'), ('complete', 'завершен')], default='open', max_length=50, verbose_name='статус платежа'),
        ),
        migrations.AddField(
            model_name='payment',
            name='session_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='номер сесси для оплаты'),
        ),
    ]
