# Generated by Django 4.2.7 on 2024-02-27 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_payment_payment_status_payment_session_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='session_id',
        ),
    ]
