# Generated by Django 4.2.7 on 2024-03-02 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_payment_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='номер сессии платежа'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_link',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='ссылка платежа'),
        ),
    ]
