# Generated by Django 4.2.7 on 2024-02-24 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_coursesubscribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.PositiveIntegerField(blank=True, default=5000, null=True, verbose_name='цена'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='price',
            field=models.PositiveIntegerField(blank=True, default=1000, null=True, verbose_name='цена'),
        ),
    ]
